clear; close all; clc


a   =   CLT_Material(E1         =   170e3,...
                     E2         =   10e3,...
                     G12        =   13e3,...
                     v12        =   0.3,...
                     Name       =   'IM7',...
                     Verbose    =   false);
    
a.addFailureTW(s1t       =   2.723e3,...
               s1c       =   1.2e3,...
               s2t       =   127,...
               s2c       =   200,...
               t12       =   95.8,...
               F12       =   0);
                 
b   =   CLT_Laminate(Stack          =   [0 90 90 0],...
                     Material       =   a,...
                     Thickness      =   0.15,...
                     Symmetric      =   false,...
                     RepeatLeft     =   1,...
                     RepeatRight    =   1,...
                     Verbose        =   true);
                 
b.calculateBuckling(Lx      =   100,...
                    Ly      =   100,...
                    k       =   0.5,...
                    BC      =   'S4',...
                    DisplayPlot     =   true,...
                    DisplayTable    =   true);
 
b.ProgressiveFailureAnalysis(Nx    =   0,...
                             Ny    =   0,...
                             Nxy   =   0,...
                             Mx    =   0,...
                             My    =   0,...
                             Mxy   =   0,...
                             Verbose   =   true);
                 
% [a,~,c,~] = b.calculateMacroBehavior()     
                 
% If you want to plot just E1 as a function of angles:
% [test] = a.calculateE1Parametric(Angles  =   linspace(0,90,100));
% 
% figure
% plot(linspace(0,90,100), test);
